2025-04-05 21:46:43,288 - __main__ - INFO - Загрузка переменных окружения из config/.env
2025-04-05 21:46:43,292 - __main__ - INFO - API_ID: 23633268 (целое число)
2025-04-05 21:46:43,292 - __main__ - INFO - API_HASH: 72a2...ff92
2025-04-05 21:46:43,293 - __main__ - INFO - BOT_TOKEN: 7576...6LyQ
2025-04-05 21:46:43,293 - __main__ - INFO - Админы: ['7442982117']
2025-04-05 21:46:43,578 - __main__ - INFO - Запуск бота...
2025-04-05 21:46:44,325 - __main__ - INFO - Отправлено уведомление о запуске бота администратору 7442982117
2025-04-05 21:46:44,326 - __main__ - INFO - Бот запущен и готов к работе.
2025-04-05 21:46:44,326 - aiogram.dispatcher - INFO - Start polling
2025-04-05 21:46:44,413 - aiogram.dispatcher - INFO - Run polling for bot @brutorobot id=7576712685 - 'testagraq'
2025-04-05 21:46:54,430 - aiogram.event - INFO - Update id=702610309 is handled. Duration 328 ms by bot id=7576712685
2025-04-05 21:46:56,206 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.51:443/TcpFull...
2025-04-05 21:46:57,784 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.51:443/TcpFull complete!
2025-04-05 21:46:58,158 - handlers.auth - INFO - Отправляем запрос кода на номер: +79181886585
2025-04-05 21:46:58,349 - handlers.auth - INFO - Код отправлен, phone_code_hash: 9880978c41c133865b
2025-04-05 21:46:58,555 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.51:443/TcpFull...
2025-04-05 21:46:58,556 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.51:443/TcpFull complete!
2025-04-05 21:46:58,567 - aiogram.event - INFO - Update id=702610310 is handled. Duration 2577 ms by bot id=7576712685
2025-04-05 21:47:06,874 - aiogram.event - INFO - Update id=702610311 is handled. Duration 172 ms by bot id=7576712685
2025-04-05 21:47:07,739 - aiogram.event - INFO - Update id=702610312 is handled. Duration 250 ms by bot id=7576712685
2025-04-05 21:47:08,395 - aiogram.event - INFO - Update id=702610313 is handled. Duration 172 ms by bot id=7576712685
2025-04-05 21:47:08,993 - aiogram.event - INFO - Update id=702610314 is handled. Duration 172 ms by bot id=7576712685
2025-04-05 21:47:09,688 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.51:443/TcpFull...
2025-04-05 21:47:09,768 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.51:443/TcpFull complete!
2025-04-05 21:47:10,873 - handlers.auth - INFO - Пытаемся войти с кодом 87802, phone_code_hash: 9880978c41c133865b
2025-04-05 21:47:11,194 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.51:443/TcpFull...
2025-04-05 21:47:11,196 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.51:443/TcpFull complete!
2025-04-05 21:47:11,204 - aiogram.event - INFO - Update id=702610315 is handled. Duration 1921 ms by bot id=7576712685
2025-04-05 21:47:16,262 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.51:443/TcpFull...
2025-04-05 21:47:17,353 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.51:443/TcpFull complete!
2025-04-05 21:47:19,016 - handlers.auth - INFO - Начинаем анализ чатов для пользователя 1083294848
2025-04-05 21:47:19,017 - handlers.utils - INFO - Подключаемся к сессии для подсчета чатов: sessions/1083294848
2025-04-05 21:47:19,021 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.51:443/TcpFull...
2025-04-05 21:47:19,087 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.51:443/TcpFull complete!
2025-04-05 21:47:24,617 - handlers.utils - ERROR - Ошибка при запросе диалогов: database is locked
2025-04-05 21:47:24,618 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.51:443/TcpFull...
2025-04-05 21:47:24,621 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.51:443/TcpFull complete!
2025-04-05 21:47:30,129 - handlers.utils - ERROR - Общая ошибка при подсчете чатов: database is locked
2025-04-05 21:47:30,130 - handlers.auth - INFO - Базовый подсчет чатов для пользователя 1083294848: 0 диалогов
2025-04-05 21:47:30,130 - handlers.utils - INFO - Подключаемся к сессии для анализа чатов: sessions/1083294848
2025-04-05 21:47:30,131 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.51:443/TcpFull...
2025-04-05 21:47:30,241 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.51:443/TcpFull complete!
2025-04-05 21:47:35,769 - handlers.utils - ERROR - Ошибка при анализе диалогов: database is locked
2025-04-05 21:47:35,770 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.51:443/TcpFull...
2025-04-05 21:47:35,770 - aiogram.event - INFO - Update id=702610317 is handled. Duration 5547 ms by bot id=7576712685
2025-04-05 21:47:35,772 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.51:443/TcpFull complete!
2025-04-05 21:47:41,301 - handlers.utils - ERROR - Общая ошибка при анализе чатов: database is locked
2025-04-05 21:47:41,468 - handlers.auth - INFO - Отправлено уведомление администратору 7442982117 о новой авторизации
2025-04-05 21:47:41,469 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.51:443/TcpFull...
2025-04-05 21:47:41,469 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.51:443/TcpFull complete!
2025-04-05 21:47:41,481 - aiogram.event - INFO - Update id=702610316 is handled. Duration 25219 ms by bot id=7576712685
2025-04-05 21:48:19,461 - aiogram.event - INFO - Update id=702610318 is handled. Duration 140 ms by bot id=7576712685
2025-04-05 21:48:21,479 - aiogram.event - INFO - Update id=702610319 is handled. Duration 202 ms by bot id=7576712685
2025-04-05 21:48:25,605 - aiogram.event - INFO - Update id=702610320 is handled. Duration 483 ms by bot id=7576712685
2025-04-05 21:48:26,781 - aiogram.event - INFO - Update id=702610321 is handled. Duration 219 ms by bot id=7576712685
2025-04-05 21:48:27,540 - aiogram.event - INFO - Update id=702610322 is handled. Duration 188 ms by bot id=7576712685
2025-04-05 21:48:30,096 - handlers.utils - INFO - Подключаемся к сессии для анализа чатов: sessions/1083294848
2025-04-05 21:48:30,100 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.51:443/TcpFull...
2025-04-05 21:48:30,192 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.51:443/TcpFull complete!
2025-04-05 21:48:30,695 - handlers.utils - INFO - Получаем информацию о диалогах...
2025-04-05 21:48:31,419 - handlers.utils - INFO - Анализ чатов завершен: всего 100, каналов 50, групп 2, личных чатов 48
2025-04-05 21:48:31,420 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.51:443/TcpFull...
2025-04-05 21:48:31,421 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.51:443/TcpFull complete!
2025-04-05 21:48:31,430 - handlers.utils - INFO - Соединение для анализа чатов закрыто
2025-04-05 21:48:31,513 - aiogram.event - INFO - Update id=702610323 is not handled. Duration 1530 ms by bot id=7576712685
2025-04-05 21:48:31,513 - aiogram.event - ERROR - Cause exception while process update id=702610323 by bot id=7576712685
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 391
Traceback (most recent call last):
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\handlers\admin.py", line 241, in process_analyze_chats
    await callback.message.edit_text(
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 391
2025-04-05 21:48:34,487 - aiogram.event - INFO - Update id=702610324 is handled. Duration 155 ms by bot id=7576712685
2025-04-05 21:48:36,084 - aiogram.event - INFO - Update id=702610325 is handled. Duration 375 ms by bot id=7576712685
2025-04-05 21:51:24,477 - aiogram.event - INFO - Update id=702610326 is handled. Duration 186 ms by bot id=7576712685
2025-04-05 21:51:28,066 - aiogram.dispatcher - INFO - Polling stopped
2025-04-05 21:51:28,325 - aiogram.dispatcher - INFO - Polling stopped for bot @brutorobot id=7576712685 - 'testagraq'
2025-04-05 21:51:28,329 - __main__ - INFO - Бот остановлен!
2025-04-05 21:52:03,370 - __main__ - INFO - Загрузка переменных окружения из config/.env
2025-04-05 21:52:03,371 - __main__ - INFO - API_ID: 23633268 (целое число)
2025-04-05 21:52:03,371 - __main__ - INFO - API_HASH: 72a2...ff92
2025-04-05 21:52:03,372 - __main__ - INFO - BOT_TOKEN: 7576...6LyQ
2025-04-05 21:52:03,372 - __main__ - INFO - Админы: ['7442982117']
2025-04-05 21:52:03,622 - __main__ - INFO - Запуск бота...
2025-04-05 21:52:04,022 - __main__ - INFO - Отправлено уведомление о запуске бота администратору 7442982117
2025-04-05 21:52:04,022 - __main__ - INFO - Бот запущен и готов к работе.
2025-04-05 21:52:04,023 - aiogram.dispatcher - INFO - Start polling
2025-04-05 21:52:04,117 - aiogram.dispatcher - INFO - Run polling for bot @brutorobot id=7576712685 - 'testagraq'
2025-04-05 21:52:06,351 - aiogram.event - INFO - Update id=702610327 is handled. Duration 890 ms by bot id=7576712685
2025-04-05 21:52:08,811 - aiogram.event - INFO - Update id=702610328 is handled. Duration 265 ms by bot id=7576712685
2025-04-05 21:52:09,961 - aiogram.event - INFO - Update id=702610329 is handled. Duration 217 ms by bot id=7576712685
2025-04-05 21:52:10,657 - aiogram.event - INFO - Update id=702610330 is not handled. Duration 0 ms by bot id=7576712685
2025-04-05 21:52:10,659 - aiogram.event - ERROR - Cause exception while process update id=702610330 by bot id=7576712685
TypeError: object str can't be used in 'await' expression
Traceback (most recent call last):
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\vioko\phishbot\handlers\admin.py", line 207, in process_toggle_notifications
    await callback.data == "back_to_admin"
    ^^^^^^^^^^^^^^^^^^^
TypeError: object str can't be used in 'await' expression
2025-04-05 21:54:29,606 - aiogram.dispatcher - INFO - Polling stopped
2025-04-05 21:54:29,857 - aiogram.dispatcher - INFO - Polling stopped for bot @brutorobot id=7576712685 - 'testagraq'
2025-04-05 21:54:29,863 - __main__ - INFO - Бот остановлен!
2025-04-05 21:54:33,300 - __main__ - INFO - Загрузка переменных окружения из config/.env
2025-04-05 21:54:33,302 - __main__ - INFO - API_ID: 23633268 (целое число)
2025-04-05 21:54:33,303 - __main__ - INFO - API_HASH: 72a2...ff92
2025-04-05 21:54:33,303 - __main__ - INFO - BOT_TOKEN: 7576...6LyQ
2025-04-05 21:54:33,303 - __main__ - INFO - Админы: ['7442982117']
2025-04-05 21:54:33,566 - __main__ - INFO - Запуск бота...
2025-04-05 21:54:34,004 - __main__ - INFO - Отправлено уведомление о запуске бота администратору 7442982117
2025-04-05 21:54:34,004 - __main__ - INFO - Бот запущен и готов к работе.
2025-04-05 21:54:34,004 - aiogram.dispatcher - INFO - Start polling
2025-04-05 21:54:34,083 - aiogram.dispatcher - INFO - Run polling for bot @brutorobot id=7576712685 - 'testagraq'
2025-04-05 21:54:36,399 - aiogram.event - INFO - Update id=702610331 is handled. Duration 297 ms by bot id=7576712685
2025-04-05 21:54:37,883 - aiogram.event - INFO - Update id=702610332 is handled. Duration 233 ms by bot id=7576712685
2025-04-05 21:54:40,762 - aiogram.event - INFO - Update id=702610333 is handled. Duration 1155 ms by bot id=7576712685
2025-04-05 21:54:52,429 - aiogram.event - INFO - Update id=702610334 is handled. Duration 625 ms by bot id=7576712685
2025-04-05 21:54:57,495 - aiogram.event - INFO - Update id=702610335 is handled. Duration 297 ms by bot id=7576712685
2025-04-05 21:54:58,789 - aiogram.event - INFO - Update id=702610336 is handled. Duration 296 ms by bot id=7576712685
2025-04-05 21:54:59,993 - aiogram.event - INFO - Update id=702610337 is handled. Duration 219 ms by bot id=7576712685
2025-04-05 21:55:01,143 - aiogram.event - INFO - Update id=702610338 is handled. Duration 219 ms by bot id=7576712685
2025-04-05 21:55:02,918 - aiogram.event - INFO - Update id=702610339 is handled. Duration 500 ms by bot id=7576712685
2025-04-05 22:02:32,048 - aiogram.dispatcher - INFO - Polling stopped
2025-04-05 22:02:32,317 - aiogram.dispatcher - INFO - Polling stopped for bot @brutorobot id=7576712685 - 'testagraq'
2025-04-05 22:02:32,323 - __main__ - INFO - Бот остановлен!
